# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      run: cd frontend && npm install
    - name: Build React components
      run: cd frontend && npm run build
    - name: Delete current contents of src/main/resources/static
      run: rm -rf src/main/resources/static/*
    - name: Move built react app to springs static folder
      run: mv frontend/build/* src/main/resources/static/
    - name: Delete original build directory
      run: rm -r frontend/build/
    - name: commit and push updates
      run: | 
        git config --global user.name "aryaman31"
        git config --global user.email "aryamanarora31@gmail.com"

        git add -A
        git commit -m "moved build directory to static directory"
        git push

  build-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -Dmaven.test.skip=true install
  test: 
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
    - name: Test with maven
      run: ./mvnw test
